# Site settings
title: 星球国际语
SEOTitle: 星球语 - 地球家园的共通语
header-img: img/home-bg-bluestars.jpg
email: globien@outlook.com
description: "中西融合, 即学即会, 让世界沟通更容易"
keyword: "人工语言, 国际语, 世界语, 星球语, 星球国际语"
url: "https://globien.gitee.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://gitee.com/globien/globien" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you're going to be!"
sidebar-avatar: /img/about-HJ.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
# github_username:    globien
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 6a11cab9f46fe57e56a1                            #生成的clientID
  clientSecret: 27ac9ec88d1ecd4c819f7423c95b4ca66e54156a    #生成的clientSecret
  repo:  globien.github.io    #仓库名称
  owner: globien    #github用户名
  admin: globien
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Giteement 
# 关于如何集成:https://www.jianshu.com/p/f5c4633524c7
# 基于码云的评论系统(https://gitee.com/zhousiwei/giteement)
giteement:
  enable: true  # 是否启用码云评论系统
  # 是否使用官方js(false可以提升访问速度)
  remote: false
  redirect_uri: 'https://globien.gitee.io'   # 应用回调地址(请和配置的第三方应用保持一致)
  # 不能更改(网上开源项目https://github.com/Rob--W/cors-anywhere作者提供的专门用来跨域服务器的配置)
  oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token
  giteeID: 'globien'  # 你的码云账号英文名
  # 存储评论的 repo name(需要在码云仓库创建公开仓库)
  repo: 'globien'
  gitment_oauth:
    client_id: 'e7d2ae28ff2563389f190714328b3896fbd0f329240e2fd9f3ded8d208000ec4'           #client ID
    client_secret: 'c649de868686537323c7ae23ee78cad89fec5e0d676215158b1752dbf5211a0b'       #client secret

# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接，请尽量不要删除，谢谢！
friends: [
    {
        title: "星球国际语",
        href: "https://globien.github.io"
    },{
        title: "星球语互动社区",
        href: "https://tieba.baidu.com/f?kw=%E6%A0%BC%E7%BD%97%E6%AF%94%E8%A8%80&fr=home"
    },{
        title: "知乎：人造国际语",
        href: "https://zhuanlan.zhihu.com/Artificial-International-Language"
    },,{
        title: "快视点（Qtrends.now）",
        href: "https://Qtrends.now/?lang=cn"
    }
]
